export const FOOTER_HEIGHT = 30;
export const SEARCHBAR_HEIGHT = 40;
export const SEARCHBAR_PADDING = 10;
export const TITLE_HEIGHT = 80;

export const MIN_PADDING = FOOTER_HEIGHT + TITLE_HEIGHT + SEARCHBAR_PADDING;

export const MAX_PADDING = MIN_PADDING + SEARCHBAR_HEIGHT + SEARCHBAR_PADDING;
